<a href="https://colab.research.google.com/github/AlejandroJabobo/THC-tareas/blob/main/Tarea_Phyton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tarea THC**

**Integrantes:**

Joshua Raúl Ugarte

Hubert Alejandro García Jacobo


In [28]:
#1. Sumas de matrices rectangulares.
import numpy as np

# Definir las matrices que se van a sumar
M1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

M2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

# Sumar las matrices
Suma = M1 + M2

# Imprimir la matriz
print(f"la suma de las matrices es: {Suma}")

la suma de las matrices es: [[11 13 15]
 [17 19 21]
 [23 25 27]]


In [29]:
#2. Multiplicación entrada a entrada rectangulares.

# Definir las matrices que se van a sumar
M1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

M2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

 # multiplicar las entradas
Multiplicacion= M1 * M2

    # Imprimir la matriz resultado
print(f"la multiplicacion de las matrices es:{ Multiplicacion}")

la multiplicacion de las matrices es:[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [15]:
#3. La Traza
def calcular_traza():
# primero creamos una matriz 3x3 llena de ceros
    matriz = np.zeros((3, 3))

    # solicitamos al usuario que introduzca los valores de la matriz
    print("Hola! Vamos a calcular la traza de una matriz 3x3.")
    for fila in range(3):
        for columna in range(3):
            valor = float(input(f"Ingrese el valor en la posición ({fila + 1}, {columna + 1}): "))
            matriz[fila, columna] = valor

    # aqui se calcula la traza de la matriz
    traza = np.trace(matriz)

    # se imprime la matriz
    print("La matriz que has ingresado es la siguiente:")
    print(matriz)

    # se imrpime la traza
    print(f"La traza de la matriz es: {traza}")

# llamamos a la función
calcular_traza()


Hola! Vamos a calcular la traza de una matriz 3x3.
Ingrese el valor en la posición (1, 1): 1
Ingrese el valor en la posición (1, 2): 2
Ingrese el valor en la posición (1, 3): 3
Ingrese el valor en la posición (2, 1): 4
Ingrese el valor en la posición (2, 2): 5
Ingrese el valor en la posición (2, 3): 6
Ingrese el valor en la posición (3, 1): 7
Ingrese el valor en la posición (3, 2): 8
Ingrese el valor en la posición (3, 3): 9
La matriz que has ingresado es la siguiente:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
La traza de la matriz es: 15.0


In [41]:

# Definir una matriz
M1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Definir una función para realizar la transposición
def transponer(M1):
    # Crear una lista vacía donde se creará la nueva matriz
    M2 = []
    for i in range(len(M1)):
        M2.append([])
        for j in range(len(M1)):
            M2[i].append(M1[j][i])

    return M2

# Llamar a la función para calcular la transpuesta
M2 = transponer(M1)

# Imprimir la matriz transpuesta
for x in M2:
  print(x)









[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


In [23]:
#5. El máximo y mínimo elemento en una matriz.
def encontrar_maximo_minimo():
    # aqui se crea una matriz vacía de 3x3
    matriz = np.zeros((3, 3))

    # se solicita al usuario que ingrese los valores de la matriz
    for fila in range(3):
        for columna in range(3):
            valor = float(input(f"Por favor, ingresa el valor en la posición ({fila+1}, {columna+1}): "))
            matriz[fila, columna] = valor

    # encontramos el valor máximo y mínimo en la matriz
    maximo = np.max(matriz)
    minimo = np.min(matriz)

    print("La matriz que has ingresado es la siguiente:")
    print(matriz)
    print(f"El valor máximo en la matriz es: {maximo}")
    print(f"El valor mínimo en la matriz es: {minimo}")

# se llama a la función
encontrar_maximo_minimo()

Por favor, ingresa el valor en la posición (1, 1): 1
Por favor, ingresa el valor en la posición (1, 2): 2
Por favor, ingresa el valor en la posición (1, 3): 3
Por favor, ingresa el valor en la posición (2, 1): 4
Por favor, ingresa el valor en la posición (2, 2): 5
Por favor, ingresa el valor en la posición (2, 3): 6
Por favor, ingresa el valor en la posición (3, 1): 7
Por favor, ingresa el valor en la posición (3, 2): 8
Por favor, ingresa el valor en la posición (3, 3): 9
La matriz que has ingresado es la siguiente:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
El valor máximo en la matriz es: 9.0
El valor mínimo en la matriz es: 1.0


In [42]:
#6. La suma del cuadrado de los elementos de una matriz.
# Definimos una matriz
matriz = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

# Inicializar una variable para la suma de los cuadrados
suma= 0

# Recorrer la matriz y calcular la suma de los cuadrados
for x in matriz:
    for y in x:
        suma+= y ** 2

# Imprimir la suma de los cuadrados
print(f"La suma de los cuadrados de los elementos de la matriz es: {suma}", )

La suma de los cuadrados de los elementos de la matriz es:285


In [45]:
#7. La potencia de matrices.34
5
def calcular_potencia_de_matriz():
    # primero creamos una matriz vacía de 3x3
    matriz = np.zeros((3, 3))

    # le pedimos al usuario que ingrese los valores de la matriz
    for fila in range(3):
        for columna in range(3):
            valor = float(input(f"Por favor, ingresa el valor en la posición ({fila+1}, {columna+1}): "))
            matriz[fila, columna] = valor

    # le edimos al usuario que ingrese la potencia deseada
    potencia = int(input("Por favor, introduce la potencia a la que deseas elevar la matriz: "))

    # ahora calculamos la matriz elevada a la potencia requerida
    resultado = np.linalg.matrix_power(matriz, potencia)

    print("La matriz que has ingresado es la siguiente:")
    print(matriz)
    print(f"La matriz elevada a la potencia {potencia} es la siguiente:")
    print(resultado)

# para concluir llamamos a la función
calcular_potencia_de_matriz()

Por favor, ingresa el valor en la posición (1, 1): 1
Por favor, ingresa el valor en la posición (1, 2): 2
Por favor, ingresa el valor en la posición (1, 3): 3
Por favor, ingresa el valor en la posición (2, 1): 4
Por favor, ingresa el valor en la posición (2, 2): 5
Por favor, ingresa el valor en la posición (2, 3): 6
Por favor, ingresa el valor en la posición (3, 1): 7
Por favor, ingresa el valor en la posición (3, 2): 8
Por favor, ingresa el valor en la posición (3, 3): 9
Por favor, introduce la potencia a la que deseas elevar la matriz: 2
La matriz que has ingresado es la siguiente:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
La matriz elevada a la potencia 2 es la siguiente:
[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]
