<a href="https://colab.research.google.com/github/AlejandroJabobo/THC-tareas/blob/main/THC_Hubert_Alejandro_Garcia_Jacobo_19_10_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array ([1,2,3,4,5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

arr = np.array (45)

print(arr)

45


In [ ]:
import numpy as np

arr = np.array ([[1,2,3],[4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

arr = np.array ([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
import numpy as np

a = np.array (45)
b = np.array ([1,2,3,4,5])
c = np.array ([[1,2,3],[4,5,6]])
d = np.array ([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim,a.shape)
print(b.ndim,b.shape)
print(c.ndim,c.shape)
print(d.ndim,d.shape)


0 ()
1 (5,)
2 (2, 3)
3 (2, 2, 3)


In [ ]:
import numpy as np

arr = np.array ([1,2,3,4,5],ndmin=5)

print(arr)

[[[[[1 2 3 4 5]]]]]


In [ ]:
import numpy as np

arr = np.array ([1,2,3,4,5])

print(arr[0])

1


In [ ]:
import numpy as np
arr = np.array ([[1,2,3],[4,5,6]])

print(arr[0][2])

3


In [ ]:
import numpy as np
arr = np.array ([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr[0][1][2])

6


In [ ]:
import numpy as np
l1=[1,2,3]
l2=[4,5,6]
l3=[7,8,9]
arr = np.array ([l1,l2,l3])
suma=0
for i in range(len(arr)):
  for j in range(len(arr)):
    suma=arr[i][j]+suma

print("la suma de los elementos de la martriz es: ",suma)



la suma de los elementos de la martriz es:  45


In [ ]:
def prodpunto(a,b):
  PP=0
  for i in range(len(a)):
      PP=PP+a[i]*b[i]
  return PP
l1=[1,1,1]
l2=[1,1,1]
l3=[1,1,1]
arr2 = np.array ([l1,l2,l3])
arr3 = np.array ([l1,l2,l3])
Pp_por_renglones=np.array([0,0,0])
Pp_por_rcolumnas=np.array([0,0,0])

for i in range(len(arr2)):
  Pp_por_renglones[i]=prodpunto(arr2[i],arr3[i])

print(Pp_por_renglones)

[3 3 3]


In [ ]:
import numpy as np
def agarracol(a,col):
  nuevo=[]
  for i in range(len(a)):
    nuevo.apend(a[i,col])

  return np.array(nuevo)

l1=[1,1,1]
l2=[1,1,1]
l3=[1,1,1]
arr2 = np.array ([l1,l2,l3])
arr3 = np.array ([l1,l2,l3])
Pp_por_renglones=np.array([0,0,0])
Pp_por_rcolumnas=np.array([0,0,0])
col1=agarracol(arr2,0)
col1

for i in range(len(arr2)):
  Pp_por_rcolumnas[i]= prodpunto(agarracol(arr2,i),agarracol(arr3,i))




AttributeError: ignored