<a href="https://colab.research.google.com/github/AlejandroJabobo/THC-tareas/blob/main/THC_Hubert_Alejandro_Garcia_Jacobo_24_10_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])

print(arr[1:5])
print(arr[1:6])
print(arr[1:])
print(arr[:4])
print(arr[-5:-1])
print(arr[-7])

[2 3 4 5]
[2 3 4 5 6]
[2 3 4 5 6 7 8 9]
[1 2 3 4]
[5 6 7 8]
3


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[1:10:2])

[ 2  4  6  8 10]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[::2])
print(arr[::3])
print(arr[::4])
print(arr[::1])
print(arr[:0:1])
print(arr[0::1])

[1 3 5 7 9]
[ 1  4  7 10]
[1 5 9]
[ 1  2  3  4  5  6  7  8  9 10]
[]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1,:])
print(arr[0:3,4])

[ 6  7  8  9 10]
[ 5 10]


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[:3,1])

[2 5 8]


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0:2,1:5])

[[ 2  3  4  5]
 [ 7  8  9 10]]


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr[0:1,1:4])

print(arr[0:2,1:4])

print(arr[0:3,1:4])

[[2 3 4]]
[[2 3 4]
 [7 8 9]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [ ]:
arr= np.array([1,2,3,4,5,4,4])

x=np.where(arr==4)
print(x)
y=np.where(arr%2==0)
print(y)

(array([3, 5, 6]),)
(array([1, 3, 5, 6]),)


In [ ]:
arr=np.array([40,50,60,70])

newarr=arr[filter_arr]

filter_arr= arr>50

print(filter_arr)
print(newarr)

[False False  True  True]
[60 70]


In [ ]:
x=np.array([1,2,3])
y=np.array([4,5,6])

suma=x+y
resta= y-x
mult= x*y
div= y/x
print(f"La suma es {suma}")
print(f"La resta es {resta}")
print(f"La multiplicación es {mult}")
print(f"La división es {div}")

La suma es [5 7 9]
La resta es [3 3 3]
La multiplicación es [ 4 10 18]
La división es [4.  2.5 2. ]


In [ ]:
print(np.pi)

3.141592653589793


In [ ]:
angulos=np.array([0,np.pi/2,np.pi])
seno=np.sin(angulos)
print(seno)


[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [ ]:
angulos=np.array([0,np.pi/2,np.pi])
coseno=np.cos(angulos)
print(coseno)

[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [ ]:
x=np.array(list(range(1,8)))
print(x)

[1 2 3 4 5 6 7]


In [ ]:
x=np.array(list(range(1,9)))
matriz= x.reshape(2,4)
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
x.reshape(-1,1).shape

(8, 1)

In [ ]:
x=np.linspace(0,4,5)
x

array([0., 1., 2., 3., 4.])

In [ ]:
np.random.uniform(0,1,3)

array([0.34016781, 0.33376782, 0.70060683])

In [ ]:
np.random.randint(0,10,5)

array([4, 3, 3, 3, 4])

In [2]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
x=int(input("esccribe un numero: "))
filter_arr= arr >= x
newarr=arr[filter_arr]
print(f"tu numero esta entre: {newarr}")
print("1= Si")
print("2= No")
y=int(input())
if y==1:
  np.random.randint(x,10,5)


NameError: ignored